/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PdfToolsRouteImport } from './routes/pdf-tools'
import { Route as MediaToolsRouteImport } from './routes/media-tools'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToolsRoute = PdfToolsRouteImport.update({
  id: '/pdf-tools',
  path: '/pdf-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaToolsRoute = MediaToolsRouteImport.update({
  id: '/media-tools',
  path: '/media-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/media-tools': typeof MediaToolsRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/media-tools': typeof MediaToolsRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/media-tools': typeof MediaToolsRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/media-tools' | '/pdf-tools' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/media-tools' | '/pdf-tools' | '/settings'
  id: '__root__' | '/' | '/media-tools' | '/pdf-tools' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MediaToolsRoute: typeof MediaToolsRoute
  PdfToolsRoute: typeof PdfToolsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-tools': {
      id: '/pdf-tools'
      path: '/pdf-tools'
      fullPath: '/pdf-tools'
      preLoaderRoute: typeof PdfToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-tools': {
      id: '/media-tools'
      path: '/media-tools'
      fullPath: '/media-tools'
      preLoaderRoute: typeof MediaToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MediaToolsRoute: MediaToolsRoute,
  PdfToolsRoute: PdfToolsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
